# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify at least Windows Server 2022 21H2 installed
        allowPrerelease: true
      settings:
        MinVersion: '10.0.20347' # Needs to be actual-1 - https://github.com/microsoft/winget-cli/issues/3654
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: pwsh
      directives:
        description: Install PowerShell
        allowPrerelease: true # must be true because Microsoft.WinGet.DSC is pre-release
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bicep
      directives:
        description: Install Bicep
        allowPrerelease: true
      settings:
        id: Microsoft.Bicep
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azcli
      directives:
        description: Install Azure CLI
        allowPrerelease: true
      settings:
        id: Microsoft.AzureCLI
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: func
      directives:
        description: Install Azure Functions Core Tools
        allowPrerelease: true
      settings:
        id: Microsoft.Azure.FunctionsCoreTools
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: wingit
      directives:
        description: Install Git for Windows
        allowPrerelease: true
      settings:
        id: Microsoft.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vs2022
      directives:
        description: Install Visual Studio 2022 Enterprise
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Enterprise
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    # - resource: Microsoft.VisualStudio.DSC/VSComponents
    #   dependsOn:
    #     - vsPackage
    #   directives:
    #     description: Install required VS workloads from vsconfig file
    #     allowPrerelease: false
    #   settings:
    #     productId: Microsoft.VisualStudio.Product.Community
    #     channelId: VisualStudio.17.Release
    #     vsConfigFile: '${WinGetConfigRoot}\..\.vsconfig'
    #     includeRecommended: true
  configurationVersion: 0.2.0
